### ISSUE TITLE
You must use Bundler 2 or greater with this lockfile!

### ISSUE THREAD

**Issue by BaseMax** [agentd00nut/jekyll-build-optional-deploy-gh-pages#1]
Hello sir;

> [!] - Gemfile not defined; defaulting to GemFile
[!] - DEPLOY_SITE is not set.  Defaulting to 'true'
[!] - BUILD_DIR is not set. Assuming the site is building to _site/
[!] - Installing Gem Bundle
You must use Bundler 2 or greater with this lockfile.
[!] - Jekyll Version: [!] - Building 
bundler: command not found: jekyll

My GitHub Action:

```
name: Jekyll Build - Deploy

on:
  push:
    branches:
    - main

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Building a jekyll site from configured directory, maybe deploying it.
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_KEY }}
          GITHUB_REPOSITORY: ${{ secrets.MY_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.MY_ACTOR }}
          JEKYLL_ROOT: "./"
          REMOTE_BRANCH: "gh-pages"
        uses: agentd00nut/jekyll-build-optional-deploy-gh-pages@master
```

Log of GitHub action:

```
Run actions/checkout@v1
  with:
    clean: true
Syncing repository: ***
git version
git version 2.32.0
git lfs version
git-lfs/2.13.3 (GitHub; linux amd64; go 1.16.2)
git init "/home/runner/work/***"
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/runner/work/***/.git/
git remote add origin https://github.com/***
git config gc.auto 0
git config --get-all http.https://github.com/***.extraheader
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/*
remote: Enumerating objects: 3303, done.        
remote: Counting objects:   0% (1/1262)        
Resolving deltas: 100% (1814/1814)
Resolving deltas: 100% (1814/1814), done.
From https://github.com/***
 * [new branch]      gh-pages   -> origin/gh-pages
 * [new branch]      jeykll     -> origin/jeykll
 * [new branch]      main       -> origin/main
 * [new branch]      old        -> origin/old
git checkout --progress --force ce803415f9a12fbe0586e23f832a3acb2b9fbc4b
Note: switching to 'ce803415f9a12fbe0586e23f832a3acb2b9fbc4b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at ce80341 Create jekyll-build-deploy.yml
```

And the last:

```
/usr/bin/docker run --name a33c172800a11495142b096f6e6d4c3654c74_5d5a0c --label 8a33c1 --workdir /github/workspace --rm -e GITHUB_TOKEN -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e JEKYLL_ROOT -e REMOTE_BRANCH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/***":"/github/workspace" 8a33c1:72800a11495142b096f6e6d4c3654c74
[!] - Entrypoint has started
[!] - Gemfile not defined; defaulting to GemFile
[!] - DEPLOY_SITE is not set.  Defaulting to 'true'
[!] - BUILD_DIR is not set. Assuming the site is building to _site/
[!] - Installing Gem Bundle
You must use Bundler 2 or greater with this lockfile.
[!] - Jekyll Version: [!] - Building 
bundler: command not found: jekyll
Install missing gem executables with `bundle install`
[!] - Pushing the contents of _site/ to gh-pages
[!!!!] - _site/ Not Found, Exiting
```

Gemfile.lock file: https://github.com/POSSF/POSSF/blob/main/Gemfile.lock

Thank you in advance for any advice.
